PPE\GSBBundle\Entity\Gere:
    type: entity
    table: GERE
    indexes:
        IDX_DFED7A7AD703BC08:
            columns:
                - matricule_col_ger
        IDX_DFED7A7A70E4A9D4:
            columns:
                - code_region
        IDX_DFED7A7A8602054F:
            columns:
                - JJMMAAAA_DEB
    id:
        matriculeColGer:
            associationKey: true
        codeRegion:
            associationKey: true
        jjmmaaaaDeb:
            associationKey: true
    fields:
        jjmmaaaaFin:
            type: datetime
            nullable: false
            column: JJMMAAAA_FIN
    oneToOne:
        matriculeColGer:
            targetEntity: Collaborateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_col_ger:
                    referencedColumnName: matricule_col
            orphanRemoval: false
        codeRegion:
            targetEntity: Region
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_region:
                    referencedColumnName: code_region
            orphanRemoval: false
        jjmmaaaaDeb:
            targetEntity: Calendrier
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                JJMMAAAA_DEB:
                    referencedColumnName: JJMMAAAA_DEB
            orphanRemoval: false
    lifecycleCallbacks: {  }
