PPE\GSBBundle\Entity\Prescrire:
    type: entity
    table: PRESCRIRE
    indexes:
        IDX_905658D21C5F7A71:
            columns:
                - depot_legal_prescr
        IDX_905658D261B89203:
            columns:
                - code_dosage
        IDX_905658D2A76557E5:
            columns:
                - code_individu
    id:
        depotLegalPrescr:
            associationKey: true
        codeDosage:
            associationKey: true
        codeIndividu:
            associationKey: true
    fields:
        posologie:
            type: string
            nullable: false
            length: 25
            fixed: false
    oneToOne:
        depotLegalPrescr:
            targetEntity: Medicament
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                depot_legal_prescr:
                    referencedColumnName: depot_legal
            orphanRemoval: false
        codeDosage:
            targetEntity: Dosage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_dosage:
                    referencedColumnName: code_dosage
            orphanRemoval: false
        codeIndividu:
            targetEntity: TypeIndividu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_individu:
                    referencedColumnName: code_individu
            orphanRemoval: false
    lifecycleCallbacks: {  }
