PPE\GSBBundle\Entity\RapportDeVisite:
    type: entity
    table: RAPPORT_DE_VISITE
    indexes:
        IDX_72BDCB1B6B866EF7:
            columns:
                - code_motif
        IDX_72BDCB1BD3000B9:
            columns:
                - matricule_praticien
    id:
        numRapport:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: num_rapport
            generator:
                strategy: IDENTITY
    fields:
        dateRapport:
            type: datetime
            nullable: false
            column: date_rapport
        dateVisite:
            type: datetime
            nullable: false
            column: date_visite
        bilanVisite:
            type: text
            nullable: false
            length: -1
            fixed: false
            column: bilan_visite
    manyToOne:
        codeMotif:
            targetEntity: Motif
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_motif:
                    referencedColumnName: code_motif
            orphanRemoval: false
        matriculePraticien:
            targetEntity: Praticien
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                matricule_praticien:
                    referencedColumnName: matricule_praticien
            orphanRemoval: false
    manyToMany:
        depotLegalOffre:
            targetEntity: Medicament
            cascade: {  }
            mappedBy: null
            inversedBy: numRapportOffre
            joinTable:
                name: offre
                joinColumns:
                    -
                        name: num_rapport_offre
                        referencedColumnName: num_rapport
                inverseJoinColumns:
                    -
                        name: depot_legal_offre
                        referencedColumnName: depot_legal
            orderBy: null
        depotLegalPres:
            targetEntity: Medicament
            cascade: {  }
            mappedBy: null
            inversedBy: numRapportPresente
            joinTable:
                name: presente
                joinColumns:
                    -
                        name: num_rapport_presente
                        referencedColumnName: num_rapport
                inverseJoinColumns:
                    -
                        name: depot_legal_pres
                        referencedColumnName: depot_legal
            orderBy: null
    lifecycleCallbacks: {  }
